version: '3.8'
services:
  postgres-db:
    image: postgres
    container_name: airport-management-db
    environment:
      - POSTGRES_USER=muzyka
      - POSTGRES_DB=airport-management-db
      - POSTGRES_PASSWORD=localdb
    ports:
      - "5532:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: localdb
    ports:
      - "5050:80"

volumes:
  db-data:
    driver: local